# Generated by Django 4.1.5 on 2024-02-24 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookieStands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiestand',
            name='avg_cookie_per_hour',
        ),
        migrations.RemoveField(
            model_name='cookiestand',
            name='cookie_sales',
        ),
        migrations.AddField(
            model_name='cookiestand',
            name='average_cookies_per_sale',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cookiestand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cookiestand',
            name='hourly_sales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookiestand',
            name='maximum_customers_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookiestand',
            name='minimum_customers_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookiestand',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
